export interface ITheme {
  color?: string,
  colorAlt?: string,
  backgroundColor?: string,
  backgroundColorAlt?: string,
  fontSizeS?: string,
  fontSizeM?: string,
  fontSizeL?: string,
  fontWeightS?: string,
  fontWeightM?: string,
  fontWeightL?: string,
  paddingHS?: string;
  paddingHM?: string;
  paddingHL?: string;
  paddingVS?: string;
  paddingVM?: string;
  paddingVL?: string;
  marginHS?: string;
  marginHM?: string;
  marginHL?: string;
  marginVS?: string;
  marginVM?: string;
  marginVL?: string;
  border?: string;
  borderRadius?: string;
  borderColor?: string;
  borderWidthM?: string;
  borderWidthL?: string;
  controlWidth?: string;
  controlMinWidth?: string;
  controlMaxWidth?: string;
  controlBorder?: string;
  controlBorderRadius?: string;
  controlBorderColor?: string;
  outlineColor?: string;
  outlineOffset?: string;
  transition?: string;
}